travis:
  secure:
    BINSTAR_TOKEN: ce2xgTSGyFtThQko8PvT01OO92zsVz0Vym2ZDgd601umffHoOWx8UELdm7G/ceH6sI+300WLOqWY+nDF6huoL7eRoa6BsVb6GbrpNGqnGuZA4mX9eEDBU4+eODde6wLDHruKwsD8tdyR42PRygRO1BlZPlbyMhht9hfnSr4NRNHVga+3cQOdozXp3IxPtN7pbu7EHEV7hWM1xPO2RpLDW6sTnQDj/lS+B5W62lmrEYnhrW1IzyO3knDVqEFmBXRABnUkTfQWjBA4Fc7/eNYVszVWZmfXRZ/F5UMzo6FPjMWG53MVbClTjMOwDBUJPRuQzgpt7aetiIgGhFCU2GSc3GksZL9bViCUmnGHnA3oyJ8mvCCPAitFJK2OkNx0KSt55wi+CO5elHI5cGb+waqVLsafJYHb9c2uc5KhWHmYPU398bovD9Ap4qA0b4zAbIw0ToLE4tVd3cMwNejZxzEG2xUrAVu9fwKaRnQFdgVY8YigEEBZWU6JB2HC1lx3g/3G4U+1DB2hjC6346HeVRwQ4EkMRKd6+TmagDnym2iGNhD2h1b5lr+/fUzlWqRJC7DZN0BR09JJjf4qJA2KKnXpi+uOILneITjGLQuDNV+IpzOP3CVX4StnomHFj5TYpkLD5qVg79r8iYvL1/LBW9G2hyQinP0lJAw4p8/PNe6RPt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
