travis:
  secure:
    BINSTAR_TOKEN: eLP9HjBvAYOGGthThQs7zTTDV8Sn2WehQUq1g8oHA4zUKshhQAB+Bt4zmgciWHRxfUmdzIdZ+i2A+Xfg8yhriwfpKsuK/aochQmFnxdGGWc2lf9+HA/bZHEGi0B3jsscLt9bhKMwaInLoMBHTUwmWug9+1BIRf/GnN+lauIrH4F1lRci6noE6PUME0vdhm2HvIm+2989SeZ2xbz6eXLG5p9KUegVXvN2/4VDHILuEyzhP7lwBiX/yqfoCdb4dRYBWBx+Do45pTI9mgPM/TaXmPw5dYvWa8T0z79EfEWtLU1fGTZGoGC8qybpCpCOxQAg70Iw4TXTUPIB+cEHrs7sQhsf+BaVPOjqol/1R90PJf1EY0wWgoisH8flgjn0xwbV9y072WLUQ/gKtKVo8vDEB2qsmjd5lR5t/LQAkwvymLUVHLkLrIwYzGQ+bSxGipk/qy8afZNe78j2PP0Sb1JWO7SmjshPqvtBv1w04z82bG86tA8az5t4hAehDV0Aq22bS17IWM6G4l3QMF7ax+Us3dJOxub9FCyQRkISs6kChYWxElpVc3KUbLWEfO8RUMe19KYGn89mpjWE+Ifh2w7M2r3xUlEubs5YBNjAW5haex80If6qkGsjGdoF44alrhtRT0D5X5wJaj94H2OW/qxXU1InzQj1P/7xAsqinSuTw+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
